### ISSUE TITLE
[bug] named blocks are not placed clearly

### ISSUE THREAD

**Issue by IanSSenne** [mc-build/mcb#3]
ref: [discord conversation](https://discord.com/channels/735100269414842428/736310546181390398/1199891037091541042)

resolution:
- named blocks should be placed relative to the parent user defined function

**Comment by SnaveSutit** [comment]
I think a good standard would be to put the generated folder of blocks within a `named` function at the same level as that named function.

For example, this code
```
function a {
  {
    # block a
    execute run {
      # block b
    }
  }
}
```
Would produce something like this:
```yaml
- functions:
  - a.mcfunction
  - zzz:
    0.mcfunction
    1.mcfunction
```

However, if we name block `a` like so:
```
function a {
  block my_blocks/a {
    # block a
    execute run {
      # block b
    }
  }
}
```
It would produce something like this:
```yaml
- functions:
  - a.mcfunction
  - my_blocks:
    - a.mcfunction
    - zzz:
      - 0.mcfunction
```
